// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoutingApp.API.Data;

#nullable disable

namespace RoutingApp.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250814080449_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoutingApp.API.Data.Entities.Point", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(8, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Points", (string)null);

                    b.HasDiscriminator().HasValue("Point");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RoutingApp.API.Models.DeliveryPoint", b =>
                {
                    b.HasBaseType("RoutingApp.API.Data.Entities.Point");

                    b.Property<decimal>("Weight")
                        .HasPrecision(6, 1)
                        .HasColumnType("decimal");

                    b.HasDiscriminator().HasValue("DeliveryPoint");
                });

            modelBuilder.Entity("RoutingApp.API.Models.Warehouse", b =>
                {
                    b.HasBaseType("RoutingApp.API.Data.Entities.Point");

                    b.HasDiscriminator().HasValue("Warehouse");
                });
#pragma warning restore 612, 618
        }
    }
}
