name: DB Deploy on Migration Change

on:
  push:
    paths:
      - 'RoutingApp.API/Migrations/*.cs'
      - 'RoutingApp.API/Migrations/*.sql'

env:
  DOTNET_VERSION: "8.x"
  API_PROJECT_PATH: "RoutingApp.API"

jobs:
  deploy-db:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install EF Tools
        run: |
          dotnet tool install --global dotnet-ef
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Apply EF Core Migrations
        env:
          AZURE_SQL_CONNECTION_STRING: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        run: |
          dotnet ef database update --project ${{ env.API_PROJECT_PATH }} --connection "$AZURE_SQL_CONNECTION_STRING"
